import type { IUser } from "./types";

export const data: IUser[] = [
  {
    id: 1,
    nama: "Iqbal Kurniawan",
    nip: "199508122020121001",
    email: "iqbal.kurniawan@kemenkum.go.id",
    unitKerja: "Pusat Data dan Teknologi Informasi",
    peran: "Administrator",
    status: "Aktif",
  },
  {
    id: 2,
    nama: "Dewi Sartika",
    nip: "198912032018122002",
    email: "dewi.sartika@kemenkum.go.id",
    unitKerja: "Biro Kepegawaian",
    peran: "Operator",
    status: "Aktif",
  },
  {
    id: 3,
    nama: "Budi Santoso",
    nip: "199104152019031003",
    email: "budi.santoso@kemenkum.go.id",
    unitKerja: "Inspektorat Jenderal",
    peran: "Viewer",
    status: "Aktif",
  },
  {
    id: 4,
    nama: "Rina Maharani",
    nip: "199307212021122004",
    email: "rina.maharani@kemenkum.go.id",
    unitKerja: "Direktorat Jenderal AHU",
    peran: "Operator",
    status: "Nonaktif",
  },
  {
    id: 5,
    nama: "Andi Wijaya",
    nip: "198806172017011005",
    email: "andi.wijaya@kemenkum.go.id",
    unitKerja: "Sekretariat Jenderal",
    peran: "Administrator",
    status: "Aktif",
  },
  {
    id: 6,
    nama: "Siti Aminah",
    nip: "199001112019022006",
    email: "siti.aminah@kemenkum.go.id",
    unitKerja: "Biro Perencanaan",
    peran: "Operator",
    status: "Aktif",
  },
  {
    id: 7,
    nama: "Ahmad Fauzi",
    nip: "198707202016011007",
    email: "ahmad.fauzi@kemenkum.go.id",
    unitKerja: "Direktorat Jenderal Imigrasi",
    peran: "Viewer",
    status: "Aktif",
  },
  {
    id: 8,
    nama: "Maya Sari",
    nip: "199205142020122008",
    email: "maya.sari@kemenkum.go.id",
    unitKerja: "Direktorat Jenderal Pemasyarakatan",
    peran: "Operator",
    status: "Aktif",
  },
  {
    id: 9,
    nama: "Yoga Pratama",
    nip: "199609022022031009",
    email: "yoga.pratama@kemenkum.go.id",
    unitKerja: "Pusat Strategi Kebijakan",
    peran: "Viewer",
    status: "Nonaktif",
  },
  {
    id: 10,
    nama: "Nina Melati",
    nip: "199311082021122010",
    email: "nina.melati@kemenkum.go.id",
    unitKerja: "Biro Hukum",
    peran: "Operator",
    status: "Aktif",
  },
];
